# Generated by Django 4.2.6 on 2023-11-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='auther',
            new_name='user',
        ),
    ]
